name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          APP_DIR: /ci_cd
          PORT: ${{ secrets.PORT }}
          DB_URI: ${{secrets.DB_URI}}
          EMAIL: ${{secrets.EMAIL}}
          APP_PASS: ${{secrets.APP_PASS}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          DOMAIN: ${{secrets.DOMAIN}}
          CLOUDINARY_URL: ${{secrets.CLOUDINARY_URL}}
          CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
          CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
          CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
        run: |
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          ssh $USER@$HOST "
            if [ ! -d $APP_DIR ]; then
              mkdir -p $APP_DIR
              git clone https://github.com/murodismo/cicd.git $APP_DIR
            else
              cd $APP_DIR
              git pull origin main
            fi

            cd $APP_DIR
            echo 'PORT=${PORT}' > .env
            npm install
            npm run build

            if pm2 list | grep -q 'ci_cd_app'; then
              pm2 restart ci_cd_app
            else
              pm2 start dist/main.js --name ci_cd_app
            fi

            pm2 save
          "
        shell: bash
