name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Deploy to server
        run: |
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

          # Create a temporary .env file
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "DB_URI=${{ secrets.DB_URI }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "APP_PASS=${{ secrets.APP_PASS }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "DOMAIN=${{ secrets.DOMAIN }}" >> .env
          echo "CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env

          # Send .env to remote server
          scp -o StrictHostKeyChecking=no .env ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/tmp/project.env

          # SSH into server and deploy
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash -s' <<'ENDSSH'
            set -x
            APP_DIR="/ci_cd"
            mkdir -p $APP_DIR
            cd $APP_DIR

            if [ ! -d ".git" ]; then
              git clone https://github.com/murodismo/cicd.git .
            else
              git pull origin main
            fi

            mv /tmp/project.env .env

            npm install
            npm run build

            if pm2 list | grep -q "ci_cd_app"; then
              pm2 restart ci_cd_app
            else
              pm2 start dist/main.js --name ci_cd_app
            fi

            pm2 save
          ENDSSH
        shell: bash
